name: CI

on:
  schedule:
    - cron: '58 19 * * *'

jobs:
  run_script_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Run script
        run: |
          python PythonRPA/main.py > output.log 
          
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.live.com
          server_port: 587
          username: ${{ secrets.HOTMAIL_EMAIL }}
          password: ${{ secrets.HOTMAIL_PASS }}
          subject: "CI Pipeline Notification"
          body: "Seu pipeline foi executado com sucesso!"
          to: ${{ secrets.HOTMAIL_EMAIL }}
