name: CI

on:
  schedule:
    - cron: '*/2 * * * *'  # Executar a cada 2 minutos

jobs:
  run_script_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip show playwright  # Verificar a instalação do Playwright
          playwright install   # Instalar o Playwright

      - name: Verify installed dependencies
        run: |
          pip list  # Lista todas as dependências instaladas

      - name: Verify virtual environment
        run: |
          source venv/bin/activate
          python --version  # Verifica a versão do Python no ambiente virtual

      - name: Verify module availability
        run: |
          python -c "import playwright"  # Verifica se o módulo Playwright está disponível

      - name: Run script
        run: |
          source venv/bin/activate
          python main.py 
          
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.live.com
          server_port: 587
          username: ${{ secrets.HOTMAIL_EMAIL }}
          password: ${{ secrets.HOTMAIL_PASS }}
          subject: "CI Pipeline Notification"
          body: "Seu pipeline foi executado com sucesso!"
          to: ${{ secrets.HOTMAIL_EMAIL }}
