name: CI

on:
  schedule:
    - cron: '*/2 * * * *'  # Executar a cada 2 minutos

jobs:
  run_script_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install playwright globally
        run: |
          pip install playwright
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Download Playwright with dependencies
        run: |
          python -m playwright install

      - name: Verify virtualenv path
        run: |
          source venv/bin/activate
          echo $PATH

      - name: Verificar instalação do Playwright
        run: |
          source venv/bin/activate
          npx playwright --version

      - name: Verify virtual environment
        run: |
          source venv/bin/activate
          python --version  # Verifica a versão do Python no ambiente virtual
          pip show playwright  # Verificar o local do módulo Playwright

      - name: Verify module availability
        run: |
          source venv/bin/activate
          python -c "import playwright"  # Verifica se o módulo Playwright está disponível

      - name: Run script
        run: |
          source venv/bin/activate
          python main.py

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "CI Pipeline Notification"
          body: "Seu pipeline foi executado com sucesso!"
          to: "matheus-cmelo@hotmail.com"
          from: "matheus10.c48@gmail.com"  # Endereço de email de remetente

