name: CI

on:
  schedule:
      - cron: '*/2 * * * *'  # Executar a cada 2 minutos
    # - cron: '31 14 * * *'   Executar às 14:23 (horário de SP) hoje
    
jobs:
  run_script_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt
          playwright install

      - name: Run script
        run: |
          source venv/bin/activate
          python main.py 
          
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.live.com
          server_port: 587
          username: ${{ secrets.HOTMAIL_EMAIL }}
          password: ${{ secrets.HOTMAIL_PASS }}
          subject: "CI Pipeline Notification"
          body: "Seu pipeline foi executado com sucesso!"
          to: ${{ secrets.HOTMAIL_EMAIL }}
